#!/bin/bash

set -e

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# 環境変数読み込み
LOAD_ENV_SCRIPT="${SCRIPT_DIR}/load_env.sh"
if [ -f "$LOAD_ENV_SCRIPT" ]; then
    source "$LOAD_ENV_SCRIPT"
    load_env_vars
else
    echo "Error: Cannot find load_env.sh script" >&2
    exit 1
fi

# Process
token_code=$(oathtool --totp --base32 "${TOTP_SECRET}")

# 自分のmfaのarnを設定する
credentials=$(aws sts get-session-token --profile enduring --duration-seconds 129600 --serial-number "$IAM_TOTP_MFA_ARN" --token-code "$token_code")

export AWS_ACCESS_KEY_ID=$(echo $credentials | jq -r ".Credentials.AccessKeyId")
export AWS_SESSION_TOKEN=$(echo $credentials | jq -r ".Credentials.SessionToken")
export AWS_SECRET_ACCESS_KEY=$(echo $credentials | jq -r ".Credentials.SecretAccessKey")
cat $HOME/.aws/credentials.tmpl | envsubst > $HOME/.aws/credentials
